version: '3.8'

services:
  gateway:
#    image: europe-west4-docker.pkg.dev/writeopia/writeopia-images/writeopia-backend:v2
    build:
      context: . # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: gateway-app
    environment:
      - JWT_SECRET="somesecret"
